---
title: "Data Wrangling excercises"
author: "Haoran Zhang"
date: "4/16/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = TRUE, eval = TRUE, warning = FALSE}
library(tidyverse)
library(nycflights13)
```

## Exercise 1
```{r, echo = TRUE, eval = TRUE, error = TRUE}
people <- tribble(
  ~name,            ~key,     ~value,
  #---------------/---------/--------
  "Ousmane Diaby",    "age",      23,
  "Ousmane Diaby", "height",     196,
  "Ousmane Diaby",    "age",      33,
  "Rich Eldh",        "age",      23,
  "Rich Eldh",     "height",     195
)

people %>% 
  group_by(name, key) %>% 
  mutate(id = row_number()) %>% 
  spread(key, value)
```

## Exercise 2
```{r, echo = TRUE}
preg <- tribble(
  ~pregnant, ~male, ~female,
  #--------/------/---------
  "yes",        NA,      10,
  "no",         20,      12
)

preg %>%
  gather ('male', 'female', key = 'sex', value = 'cases' )

```

## Exercise 3
```{r, echo = TRUE}
tibble(x = c("a,b,c", "d,e,f,g", "h,i,j")) %>% 
  separate(x, c("one", "two", "three"))
# R returns a warning message because the second column has more than three values.
# In order to fix this, we need to change the default setting of extra value into 'merge'.
tibble(x = c("a,b,c", "d,e,f,g", "h,i,j")) %>% 
  separate(x, c("one", "two", "three"), extra = 'merge')

```

## Exercise 4
```{r, echo = TRUE}
tibble(x = c("a,b,c", "d,e,f", "h,i,j")) %>% 
  separate(x, c("one", "two", "three"), remove = FALSE)
```

## Exercise 5
```{r, echo = TRUE}
who %>%
  gather(code, value, new_sp_m014:newrel_f65, na.rm = TRUE) %>% 
  mutate(code = gsub("newrel", "new_rel", code)) %>%
  separate(code, c("new", "var", "sexage")) %>% 
  select(-new, -iso2, -iso3) %>%
  separate(sexage, c("sex", "age"), sep = 1) %>%
  group_by(country, year) %>%
  mutate (total_cases = sum(value)) %>%
  filter (country %in% c('China', 'India', 'Bangladesh')) %>%
  ggplot ( aes(x = year, y = total_cases, color = country)) +
  geom_point() +
  geom_line()

```

## Exercise 6
```{r, echo = TRUE}
flights %>%
  inner_join(weather, by = c('origin', 'year', 'month', 'day', 'hour') %>%
  mutate(
    wind_gust_binned = cut(wind_gust, break = seq(0, max(wind_gust), 5))
                           ) %>%
  group_by (wind_gust_binned) %>%
  mutate (avg_delay = mean(dep_delay, na.rm = TRUE)) %>%
  ggplot(aes(x = wind_gust_binned, y = avg_delay)) +
  geom_bar()
```
